server:
  port: 9002
spring:
  application:
    name: blog-system
  datasource:
    url: jdbc:mysql://localhost:3306/health_manager?serverTimezone=GMT&characterEncoding=utf-8&useSSL=false
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: test_user
    password: 123456
  redis:
    port: 6379
    host: 47.119.132.173
    password: 123456
mybatis:
  config-location: classpath:mybatis-config.xml
  mapper-locations: classpath*:stu/swufe/fhl/blog/mapper/*Mapper.xml



#logging:
#  pattern:
#    console: "%d{yyyy/MM/dd-HH:mm:ss} [%thread] [%-Slevel] %logger %msg%n"